/****************************************************************************
 * Automatically generated by Bun.js Bindings Generator.
 * Do not modify!
 ****************************************************************************/

#pragma once

extern "C" {
#include "quickjs.h"
}

void register_all_axjs_base(JSContext* ctx);
