/****************************************************************************
 * Automatically generated by Bun.js Bindings Generator.
 * Do not modify!
 ****************************************************************************/

#include "js-bindings/auto/axjs_base_auto.hpp"
#include "js-bindings/manual/JsBasicConversions.h"
#include "js-bindings/manual/JsCallbacks.h"

#include "axmol/scene/Node.h"

using namespace ax;

namespace ax {

void register_all_axjs_base(JSContext* ctx)
{
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue ax_ns = JS_GetPropertyStr(ctx, global, "ax");
    if (JS_IsUndefined(ax_ns))
    {
        ax_ns = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, global, "ax", ax_ns);
    }

    if (s_ax_Ref_class_id == 0)
    {
        JS_NewClassID(JS_GetRuntime(ctx), &s_ax_Ref_class_id);
        JSClassDef class_def = {
            "Ref",
            js_ax_Ref_finalizer,
            nullptr, nullptr, nullptr
        };
        JS_NewClass(JS_GetRuntime(ctx), s_ax_Ref_class_id, &class_def);
    }

    JS_FreeValue(ctx, ax_ns);
    JS_FreeValue(ctx, global);
}

} // namespace ax
