import { ClassMetadata, MethodMetadata, ParamMetadata } from "./parser";

interface GeneratorOptions {
  nsMap: Record<string, string>;
  ignoreMethods: string[];
  classesConfig: Array<{ name: string; js_name: string; is_singleton?: boolean }>;
}

export class BindingWriter {
  private moduleName: string;
  private classes: ClassMetadata[];
  private options: GeneratorOptions;
  private classMap: Map<string, ClassMetadata> = new Map();

  constructor(moduleName: string, classes: ClassMetadata[], options: GeneratorOptions) {
    this.moduleName = moduleName;
    this.classes = classes;
    this.options = options;

    for (const c of classes) {
      this.classMap.set(c.name, c);
    }
  }

  /**
   * Get the JS class name for a C++ class name.
   */
  private getJSClassName(cppName: string): string {
    const config = this.options.classesConfig.find(item => item.name === cppName);
    if (config && config.js_name) {
      return config.js_name;
    }
    // Fallback: strip namespace
    const idx = cppName.lastIndexOf("::");
    return idx === -1 ? cppName : cppName.substring(idx + 2);
  }

  /**
   * Check if a class is a singleton.
   */
  private isSingleton(cppName: string): boolean {
    const config = this.options.classesConfig.find(item => item.name === cppName);
    return !!(config && config.is_singleton);
  }

  /**
   * Check if a class should be processed.
   */
  private shouldBindClass(cppName: string): boolean {
    return this.options.classesConfig.some(item => item.name === cppName);
  }

  /**
   * Generate .hpp file content.
   */
  public generateHpp(): string {
    const upperModuleName = this.moduleName.toUpperCase();
    return `/****************************************************************************
 * Automatically generated by Bun.js Bindings Generator.
 * Do not modify!
 ****************************************************************************/

#pragma once

extern "C" {
#include "quickjs.h"
}

void register_all_axjs_${this.moduleName}(JSContext* ctx);
`;
  }

  /**
   * Generate .cpp file content.
   */
  public generateCpp(headers: string[]): string {
    let code = `/****************************************************************************
 * Automatically generated by Bun.js Bindings Generator.
 * Do not modify!
 ****************************************************************************/

#include "js-bindings/auto/axjs_${this.moduleName}_auto.hpp"
#include "js-bindings/manual/JsBasicConversions.h"
#include "js-bindings/manual/JsCallbacks.h"

`;

    // Include target headers
    for (const h of headers) {
      code += `#include "${h}"\n`;
    }
    code += "\nusing namespace ax;\n\nnamespace ax {\n\n";

    // Filter classes to only include those configured
    const targetClasses = this.classes.filter(c => this.shouldBindClass(c.name));

    // Generate binding wrapper functions for each class
    for (const cls of targetClasses) {
      code += this.generateClassWrappers(cls);
    }

    // Generate register_all function
    code += `void register_all_axjs_${this.moduleName}(JSContext* ctx)\n{\n`;
    code += `    JSValue global = JS_GetGlobalObject(ctx);\n`;
    code += `    JSValue ax_ns = JS_GetPropertyStr(ctx, global, "ax");\n`;
    code += `    if (JS_IsUndefined(ax_ns))\n`;
    code += `    {\n`;
    code += `        ax_ns = JS_NewObject(ctx);\n`;
    code += `        JS_SetPropertyStr(ctx, global, "ax", ax_ns);\n`;
    code += `    }\n\n`;

    // Ensure s_ax_Ref_class_id is initialized
    code += `    if (s_ax_Ref_class_id == 0)\n`;
    code += `    {\n`;
    code += `        JS_NewClassID(JS_GetRuntime(ctx), &s_ax_Ref_class_id);\n`;
    code += `        JSClassDef class_def = {\n`;
    code += `            "Ref",\n`;
    code += `            js_ax_Ref_finalizer,\n`;
    code += `            nullptr, nullptr, nullptr\n`;
    code += `        };\n`;
    code += `        JS_NewClass(JS_GetRuntime(ctx), s_ax_Ref_class_id, &class_def);\n`;
    code += `    }\n\n`;

    for (const cls of targetClasses) {
      const jsName = this.getJSClassName(cls.name);
      code += `    // Register ${cls.name}\n`;
      code += `    {\n`;
      code += `        JSValue proto = JS_NewObject(ctx);\n`;
      
      // Register member methods on prototype
      const memberMethods = this.groupMethods(cls.methods.filter(m => !m.isStatic && m.name !== "constructor"));
      for (const [methodName, overloads] of memberMethods.entries()) {
        if (this.options.ignoreMethods.includes(methodName)) continue;
        const wrapperName = `js_ax_${cls.shortName}_${methodName}`;
        code += `        JS_SetPropertyStr(ctx, proto, "${methodName}", JS_NewCFunction(ctx, ${wrapperName}, "${methodName}", 0));\n`;
      }

      code += `        register_class_prototype(ctx, "${cls.name}", proto);\n`;
      code += `        JS_SetClassProto(ctx, s_ax_Ref_class_id, proto);\n\n`;

      if (this.isSingleton(cls.name)) {
        // Register singleton instance getter or direct property
        // E.g. director instance
        // Look for getInstance method
        const hasGetInstance = cls.methods.some(m => m.isStatic && m.name === "getInstance");
        if (hasGetInstance) {
          code += `        // Singleton ${jsName}\n`;
          code += `        JSValue ctor = JS_NewObject(ctx);\n`;
          code += `        JS_SetPropertyStr(ctx, ax_ns, "${jsName}", ctor);\n`;
          code += `        // Also add instance getter\n`;
          const wrapperName = `js_ax_${cls.shortName}_getInstance`;
          code += `        JS_SetPropertyStr(ctx, ctor, "getInstance", JS_NewCFunction(ctx, ${wrapperName}, "getInstance", 0));\n`;
        }
      } else {
        // Normal class with constructor or static creators
        code += `        JSValue ctor = JS_NewCFunction2(ctx, js_ax_${cls.shortName}_constructor, "${jsName}", 0, JS_CFUNC_constructor, 0);\n`;
        code += `        JS_SetConstructor(ctx, ctor, proto);\n`;

        // Register static methods on constructor
        const staticMethods = this.groupMethods(cls.methods.filter(m => m.isStatic));
        for (const [methodName, overloads] of staticMethods.entries()) {
          const wrapperName = `js_ax_${cls.shortName}_${methodName}`;
          code += `        JS_SetPropertyStr(ctx, ctor, "${methodName}", JS_NewCFunction(ctx, ${wrapperName}, "${methodName}", 0));\n`;
        }

        code += `        JS_SetPropertyStr(ctx, ax_ns, "${jsName}", ctor);\n`;
      }
      code += `        JS_FreeValue(ctx, proto);\n`;
      code += `    }\n\n`;
    }

    code += `    JS_FreeValue(ctx, ax_ns);\n`;
    code += `    JS_FreeValue(ctx, global);\n`;
    code += `}\n\n} // namespace ax\n`;

    return code;
  }

  /**
   * Group methods by name.
   */
  private groupMethods(methods: MethodMetadata[]): Map<string, MethodMetadata[]> {
    const map = new Map<string, MethodMetadata[]>();
    for (const m of methods) {
      if (!map.has(m.name)) {
        map.set(m.name, []);
      }
      map.get(m.name)!.push(m);
    }
    return map;
  }

  /**
   * Generate wrapper functions for a class.
   */
  private generateClassWrappers(cls: ClassMetadata): string {
    let code = `// Wrappers for ${cls.name}\n`;

    // Group member methods
    const memberMethods = this.groupMethods(cls.methods.filter(m => !m.isStatic && m.name !== "constructor"));
    for (const [methodName, overloads] of memberMethods.entries()) {
      if (this.options.ignoreMethods.includes(methodName)) continue;
      code += this.generateMethodWrapper(cls, methodName, overloads, false);
    }

    // Group static methods
    const staticMethods = this.groupMethods(cls.methods.filter(m => m.isStatic));
    for (const [methodName, overloads] of staticMethods.entries()) {
      code += this.generateMethodWrapper(cls, methodName, overloads, true);
    }

    // Constructor wrapper (if not singleton)
    if (!this.isSingleton(cls.name)) {
      code += this.generateConstructorWrapper(cls);
    }

    return code + "\n";
  }

  /**
   * Generate constructor wrapper.
   */
  private generateConstructorWrapper(cls: ClassMetadata): string {
    let code = `static JSValue js_ax_${cls.shortName}_constructor(JSContext* ctx, JSValueConst new_target, int argc, JSValueConst* argv)\n{\n`;
    
    // QuickJS constructors create a new instance and bind prototype.
    // If the class inherits from Ref, it must be created via factory (e.g. Sprite::create()) or new, and then wrap.
    // Let's check if the class has a factory method like "create".
    const hasCreate = cls.methods.some(m => m.isStatic && m.name === "create");
    
    code += `    ${cls.name}* self = nullptr;\n`;
    if (hasCreate) {
      code += `    // Create using static create() factory\n`;
      code += `    self = ${cls.name}::create();\n`;
    } else {
      code += `    // Create using C++ new operator\n`;
      code += `    self = new ${cls.name}();\n`;
    }

    code += `    if (!self)\n`;
    code += `        return JS_NULL;\n\n`;

    code += `    JSValue proto = JS_GetPropertyStr(ctx, new_target, "prototype");\n`;
    code += `    if (JS_IsException(proto))\n`;
    code += `        return JS_EXCEPTION;\n\n`;

    code += `    JSValue obj = JS_NewObjectProtoClass(ctx, proto, s_ax_Ref_class_id);\n`;
    code += `    JS_FreeValue(ctx, proto);\n`;
    code += `    if (JS_IsException(obj))\n`;
    code += `        return JS_EXCEPTION;\n\n`;

    code += `    JS_SetOpaque(obj, self);\n`;
    if (cls.isRef) {
      code += `    self->retain();\n`;
      code += `    register_js_wrapper(ctx, self, obj);\n`;
    }

    code += `    return obj;\n`;
    code += `}\n\n`;
    return code;
  }

  /**
   * Generate method wrapper (handling overloads).
   */
  private generateMethodWrapper(cls: ClassMetadata, methodName: string, overloads: MethodMetadata[], isStatic: boolean): string {
    const wrapperName = `js_ax_${cls.shortName}_${methodName}`;
    let code = `static JSValue ${wrapperName}(JSContext* ctx, JSValueConst this_val, int argc, JSValueConst* argv)\n{\n`;

    if (!isStatic) {
      code += `    ${cls.name}* self = (${cls.name}*)JS_GetOpaque(this_val, s_ax_Ref_class_id);\n`;
      code += `    if (!self)\n`;
      code += `        return JS_ThrowTypeError(ctx, "Invalid Native Object");\n\n`;
    }

    // Group overloads by parameter count
    const overloadsByArgc = new Map<number, MethodMetadata[]>();
    for (const o of overloads) {
      const paramCount = o.params.length;
      if (!overloadsByArgc.has(paramCount)) {
        overloadsByArgc.set(paramCount, []);
      }
      overloadsByArgc.get(paramCount)!.push(o);
    }

    // Generate conditional code based on argc
    let first = true;
    for (const [paramCount, methods] of overloadsByArgc.entries()) {
      const cond = first ? "if" : "else if";
      first = false;

      code += `    ${cond} (argc == ${paramCount})\n    {\n`;

      // Implement overload checking
      for (const m of methods) {
        code += `        {\n`;
        code += `            bool ok = true;\n`;

        // Preps
        const convertedArgs: string[] = [];
        for (let i = 0; i < m.params.length; i++) {
          const p = m.params[i];
          const conv = this.getArgumentConversion(p.type, `arg${i}`, `${i}`);
          code += conv.prep + "\n";
          convertedArgs.push(conv.name);
        }

        code += `            if (ok)\n            {\n`;
        // Execute call
        const callExpr = isStatic 
          ? `${cls.name}::${methodName}(${convertedArgs.join(", ")})`
          : `self->${methodName}(${convertedArgs.join(", ")})`;
        
        code += `                ` + this.getReturnConversion(m.returnType, callExpr) + "\n";
        code += `            }\n`;
        code += `        }\n`;
      }

      code += `    }\n`;
    }

    if (!first) {
      code += `    else\n    {\n`;
      code += `        return JS_ThrowTypeError(ctx, "Invalid number of arguments");\n`;
      code += `    }\n`;
    } else {
      code += `    return JS_UNDEFINED;\n`;
    }

    // If there were no parameter overloads matched
    code += `    return JS_ThrowTypeError(ctx, "Invalid argument types");\n`;
    code += `}\n\n`;

    return code;
  }

  /**
   * Generate parameter conversion code.
   */
  private getArgumentConversion(paramType: string, paramVarName: string, argIdx: string): { prep: string; name: string } {
    // Normalize spaces around &, *, and trim
    const cleanType = paramType
      .replace(/\s+/g, " ")
      .replace(/\s*&\s*/g, "&")
      .replace(/\s*\*\s*/g, "*")
      .trim();

    if (cleanType === "int" || cleanType === "int32_t" || cleanType === "GLint") {
      return {
        prep: `            int32_t ${paramVarName} = 0;\n            ok &= jsval_to_int32(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (cleanType === "unsigned int" || cleanType === "uint32_t" || cleanType === "GLuint") {
      return {
        prep: `            uint32_t ${paramVarName} = 0;\n            ok &= jsval_to_uint32(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (cleanType === "bool") {
      return {
        prep: `            bool ${paramVarName} = false;\n            ok &= jsval_to_bool(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (cleanType === "float") {
      return {
        prep: `            float ${paramVarName} = 0.0f;\n            ok &= jsval_to_float(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (cleanType === "double") {
      return {
        prep: `            double ${paramVarName} = 0.0;\n            ok &= jsval_to_double(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "std::string" ||
      cleanType === "const std::string&" ||
      cleanType === "std::string_view" ||
      cleanType === "const std::string_view&"
    ) {
      return {
        prep: `            std::string ${paramVarName};\n            ok &= jsval_to_std_string(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "ax::Vec2" ||
      cleanType === "const ax::Vec2&" ||
      cleanType === "Vec2" ||
      cleanType === "const Vec2&"
    ) {
      return {
        prep: `            ax::Vec2 ${paramVarName};\n            ok &= jsval_to_vec2(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "ax::Size" ||
      cleanType === "const ax::Size&" ||
      cleanType === "Size" ||
      cleanType === "const Size&"
    ) {
      return {
        prep: `            ax::Size ${paramVarName};\n            ok &= jsval_to_size(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "ax::Rect" ||
      cleanType === "const ax::Rect&" ||
      cleanType === "Rect" ||
      cleanType === "const Rect&"
    ) {
      return {
        prep: `            ax::Rect ${paramVarName};\n            ok &= jsval_to_rect(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "ax::Color3B" ||
      cleanType === "const ax::Color3B&" ||
      cleanType === "Color3B" ||
      cleanType === "const Color3B&"
    ) {
      return {
        prep: `            ax::Color3B ${paramVarName};\n            ok &= jsval_to_color3b(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "ax::Color4B" ||
      cleanType === "const ax::Color4B&" ||
      cleanType === "Color4B" ||
      cleanType === "const Color4B&"
    ) {
      return {
        prep: `            ax::Color4B ${paramVarName};\n            ok &= jsval_to_color4b(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }
    if (
      cleanType === "ax::Color4F" ||
      cleanType === "const ax::Color4F&" ||
      cleanType === "Color4F" ||
      cleanType === "const Color4F&"
    ) {
      return {
        prep: `            ax::Color4F ${paramVarName};\n            ok &= jsval_to_color4f(ctx, argv[${argIdx}], &${paramVarName});`,
        name: `${paramVarName}`
      };
    }

    if (cleanType.endsWith("*")) {
      const rawType = cleanType.replace("*", "").trim();
      const isBound = this.classMap.has(rawType) || 
                      this.classMap.has("ax::" + rawType) || 
                      rawType === "Ref" || 
                      rawType === "ax::Ref";
      if (isBound) {
        return {
          prep: `            ${rawType}* ${paramVarName} = nullptr;\n            ok &= jsval_to_object<${rawType}>(ctx, argv[${argIdx}], &${paramVarName});`,
          name: `${paramVarName}`
        };
      } else {
        return {
          prep: `            // Warning: pointer to unbound type ${cleanType}\n            ok = false;`,
          name: `nullptr`
        };
      }
    }

    return {
      prep: `            // Warning: unknown type ${cleanType}\n            void* ${paramVarName} = nullptr;`,
      name: `(${cleanType})${paramVarName}`
    };
  }

  /**
   * Generate return value conversion code.
   */
  private getReturnConversion(returnType: string, expr: string): string {
    // Normalize spaces around &, *, and trim
    const cleanType = returnType
      .replace(/\s+/g, " ")
      .replace(/\s*&\s*/g, "&")
      .replace(/\s*\*\s*/g, "*")
      .trim();

    if (cleanType === "void") {
      return `${expr};\n                return JS_UNDEFINED;`;
    }
    if (cleanType === "int" || cleanType === "int32_t" || cleanType === "GLint") {
      return `return int32_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "unsigned int" || cleanType === "uint32_t" || cleanType === "GLuint") {
      return `return uint32_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "bool") {
      return `return bool_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "float") {
      return `return float_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "double") {
      return `return double_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "std::string" || cleanType === "const std::string&" || cleanType === "std::string_view" || cleanType === "const std::string_view&") {
      return `return std_string_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "ax::Vec2" || cleanType === "const ax::Vec2&" || cleanType === "Vec2" || cleanType === "const Vec2&") {
      return `return vec2_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "ax::Size" || cleanType === "const ax::Size&" || cleanType === "Size" || cleanType === "const Size&") {
      return `return size_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "ax::Rect" || cleanType === "const ax::Rect&" || cleanType === "Rect" || cleanType === "const Rect&") {
      return `return rect_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "ax::Color3B" || cleanType === "const ax::Color3B&" || cleanType === "Color3B" || cleanType === "const Color3B&") {
      return `return color3b_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "ax::Color4B" || cleanType === "const ax::Color4B&" || cleanType === "Color4B" || cleanType === "const Color4B&") {
      return `return color4b_to_jsval(ctx, ${expr});`;
    }
    if (cleanType === "ax::Color4F" || cleanType === "const ax::Color4F&" || cleanType === "Color4F" || cleanType === "const Color4F&") {
      return `return color4f_to_jsval(ctx, ${expr});`;
    }

    if (cleanType.endsWith("*")) {
      const rawType = cleanType.replace("*", "").trim();
      return `return object_to_jsval(ctx, ${expr}, "${rawType}");`;
    }

    return `// Warning: unknown return type ${cleanType}\n                return JS_NULL;`;
  }
}
